import { defineConfig } from 'vitepress'

export default defineConfig({
  base: '/openwrt-tailscale/',

  vite: {
    server: {
      watch: { usePolling: true },
      hmr: { overlay: false },
      allowedHosts: true,
    },
  },

  markdown: {
    theme: { light: 'github-light', dark: 'github-dark' },
    lineNumbers: true,
  },

  lastUpdated: true,

  sitemap: {
    hostname: 'https://gunanovo.github.io/openwrt-tailscale/'
  },

  themeConfig: {
    siteTitle: 'Tailscale for OpenWrt',
    search: { provider: 'local' },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/GuNanOvO/openwrt-tailscale' }
    ],
    footer: {
      message: 'Built with ❤️ and shared with the community.',
      copyright: 'MIT License | <a href="https://github.com/GuNanOvO/openwrt-tailscale">⭐ Star on GitHub</a> — Generated by GitHub Action on: __BUILD_DATE__ Version: __BUILD_VERSION__'
    },
    outline: { level: [2, 3], label: 'On this page' },
    docFooter: { prev: 'Previous', next: 'Next' },
    lastUpdated: { text: 'Last updated' },
    editLink: {
      pattern: 'https://github.com/GuNanOvO/openwrt-tailscale/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
  },

  locales: {
    en: {
      label: 'English',
      lang: 'en-US',
      title: 'Smaller Tailscale for OpenWrt',
      description: 'Optimized Tailscale repository for OpenWrt — smaller IPK & APK packages with UPX compression',
      head: [
        ['link', { rel: 'icon', href: '/openwrt-tailscale/favicon.ico' }],
        ['meta', { name: 'keywords', content: 'OpenWrt, Tailscale, APK, IPK, smaller packages, optimized tailscale, UPX, VPN, OpenWrt 25.12, OpenWrt 24.10' }],
      ],
      themeConfig: {
        nav: [
          { text: 'Quick Start', link: '/en/guide/quick-start' },
          { text: 'Guide', items: [
            { text: 'Introduction', link: '/en/guide/introduction' },
            { text: 'APK Install (25.12+)', link: '/en/guide/apk-setup' },
            { text: 'OPKG Install (24.10-)', link: '/en/guide/opkg-setup' },
            { text: 'One-Click Script', link: '/en/guide/install-script' },
            { text: 'Manual Install', link: '/en/guide/manual-install' },
            { text: 'Post-Install Config', link: '/en/guide/post-install' },
            { text: 'LuCI Web UI', link: '/en/guide/luci' },
            { text: 'Memory Optimization', link: '/en/guide/oom' },
          ] },
          { text: 'APK Install', link: '/en/guide/apk-setup' },
          { text: 'OPKG Install', link: '/en/guide/opkg-setup' },
          { text: 'Install Script', link: '/en/guide/install-script' },
          { text: 'Packages', link: '/en/packages' },
          { text: 'Build', items: [
            { text: 'Overview', link: '/en/build/' },
            { text: 'Build IPK', link: '/en/build/ipk' },
            { text: 'Build APK', link: '/en/build/apk' },
            { text: 'Self-Build Firmware', link: '/en/build/self-build' },
          ] },
          { text: 'Help', items: [
            { text: 'FAQ', link: '/en/reference/faq' },
            { text: 'Supported Architectures', link: '/en/reference/architectures' },
            { text: 'Security Statement', link: '/en/reference/security' },
            { text: 'GitHub', link: 'https://github.com/GuNanOvO/openwrt-tailscale' },
          ] },
        ],
        sidebar: {
          '/en/guide/': [
            { text: 'Guide', items: [
              { text: 'Introduction', link: '/en/guide/introduction' },
              { text: 'Quick Start', link: '/en/guide/quick-start' },
              { text: 'APK Install (25.12+)', link: '/en/guide/apk-setup' },
              { text: 'OPKG Install (24.10-)', link: '/en/guide/opkg-setup' },
              { text: 'One-Click Script', link: '/en/guide/install-script' },
              { text: 'Manual Install', link: '/en/guide/manual-install' },
              { text: 'Post-Install Config', link: '/en/guide/post-install' },
              { text: 'LuCI Web UI', link: '/en/guide/luci' },
              { text: 'Memory Optimization', link: '/en/guide/oom' },
            ] }
          ],
          '/en/build/': [
            { text: 'Build Guide', items: [
              { text: 'Overview', link: '/en/build/' },
              { text: 'Build IPK (24.10)', link: '/en/build/ipk' },
              { text: 'Build APK (25.12+)', link: '/en/build/apk' },
              { text: 'Self-Build Firmware', link: '/en/build/self-build' },
            ] }
          ],
          '/en/reference/': [
            { text: 'Reference', items: [
              { text: 'FAQ', link: '/en/reference/faq' },
              { text: 'Supported Architectures', link: '/en/reference/architectures' },
              { text: 'Security Statement', link: '/en/reference/security' },
            ] }
          ],
        },
      },
    },
    zh: {
      label: '简体中文',
      lang: 'zh-CN',
      title: '适用于 OpenWrt 的精简 Tailscale',
      description: '适用于 OpenWrt 的 最新的、更小的 Tailscale 软件源 — 使用 UPX 压缩的更小 IPK 和 APK 软件包',
      head: [
        ['link', { rel: 'icon', href: '/openwrt-tailscale/favicon.ico' }],
        ['meta', { name: 'keywords', content: 'OpenWrt, Tailscale, APK, IPK, OpenWrt 25.12, OpenWrt 24.10, Tailscale APK, Tailscale IPK, Tailscale Repository, OpenWrt Software Feed, smaller packages, optimized tailscale, upx compression, VPN for OpenWrt, tailscale for openwrt, install tailscale on openwrt,Tailscale 官方源, OpenWrt 安装 Tailscale, 轻量版 Tailscale, tailscale-openwrt, custom tailscale repo, opkg, apk index,latest tailscale, 最新 的 tailscale' }],
      ],
      themeConfig: {
        nav: [
          { text: '快速开始', link: '/zh/guide/quick-start' },
          { text: '指南', items: [
            { text: '项目简介', link: '/zh/guide/introduction' },
            { text: 'APK 安装 (25.12+)', link: '/zh/guide/apk-setup' },
            { text: 'OPKG 安装 (24.10-)', link: '/zh/guide/opkg-setup' },
            { text: '一键式脚本安装', link: '/zh/guide/install-script' },
            { text: '手动下载安装', link: '/zh/guide/manual-install' },
            { text: '安装后配置', link: '/zh/guide/post-install' },
            { text: 'LuCI 管理界面', link: '/zh/guide/luci' },
            { text: '内存优化', link: '/zh/guide/oom' },
          ] },
          { text: 'APK 安装', link: '/zh/guide/apk-setup' },
          { text: 'OPKG 安装', link: '/zh/guide/opkg-setup' },
          { text: '一键式脚本', link: '/zh/guide/install-script' },
          { text: '软件包', link: '/zh/packages' },
          { text: '构建', items: [
            { text: '概览', link: '/zh/build/' },
            { text: '构建 IPK', link: '/zh/build/ipk' },
            { text: '构建 APK', link: '/zh/build/apk' },
            { text: '自编译固件', link: '/zh/build/self-build' },
          ] },
          { text: '帮助', items: [
            { text: '常见问题', link: '/zh/reference/faq' },
            { text: '支持架构', link: '/zh/reference/architectures' },
            { text: '安全声明', link: '/zh/reference/security' },
            { text: 'GitHub', link: 'https://github.com/GuNanOvO/openwrt-tailscale' },
          ] },
        ],
        sidebar: {
          '/zh/guide/': [
            { text: '配置指南', items: [
              { text: '项目简介', link: '/zh/guide/introduction' },
              { text: '快速开始', link: '/zh/guide/quick-start' },
              { text: 'APK 安装 (25.12+)', link: '/zh/guide/apk-setup' },
              { text: 'OPKG 安装 (24.10-)', link: '/zh/guide/opkg-setup' },
              { text: '一键式脚本安装', link: '/zh/guide/install-script' },
              { text: '手动下载安装', link: '/zh/guide/manual-install' },
              { text: '安装后配置', link: '/zh/guide/post-install' },
              { text: 'LuCI 管理界面', link: '/zh/guide/luci' },
              { text: '内存优化', link: '/zh/guide/oom' },
            ] }
          ],
          '/zh/build/': [
            { text: '构建指南', items: [
              { text: '概览', link: '/zh/build/' },
              { text: '构建 IPK (24.10)', link: '/zh/build/ipk' },
              { text: '构建 APK (25.12+)', link: '/zh/build/apk' },
              { text: '自编译固件', link: '/zh/build/self-build' },
            ] }
          ],
          '/zh/reference/': [
            { text: '参考', items: [
              { text: '常见问题', link: '/zh/reference/faq' },
              { text: '支持架构', link: '/zh/reference/architectures' },
              { text: '安全声明', link: '/zh/reference/security' },
            ] }
          ],
        },
      },
    },
  },
})
